### ISSUE TITLE
mpv latest version is incorrect

### ISSUE THREAD

**Issue by dylanaraps** [repology/repology-rules#251]
I'm not sure if this is the right repository to open this issue, apologies.

The `mpv` version listed on repology as the latest is `0.30.0`. This doesn't exist upstream, the latest upstream version is `0.29.1`. The two distributions on repology which provide `0.30.0` are creating this version basically out of thin air. They're really using a `git` commit and calling it `0.30.0`.

Upstream issue about why `0.30.0` (or a newer version than `0.29.1`) hasn't been released: https://github.com/mpv-player/mpv/issues/6855

> There are outstanding issues that prevent a 0.30 release right now, like the removal of the stream cache probably needing to be undone, so no there's no point making a new release just because there have been 369 commits when people will then complain about the effects of not having a stream cache for the next 5 years or however long it takes before various distros stop using a specific version of mpv.

Here's what the `mpv.spec` file says from both of the mentioned repositories shipping `git` commits as releases:

```
# We package git master instead of so-called stable releases
# that have stopped happening.
# As of 2019/08/13, the last "release" is almost a year old, and the
# mpv project's definition of a "release" is
# """
# Every other month, an arbitrary git snapshot is made,
# and is assigned a 0.X.0 version number. No further maintenance is done.
# """
# So any slightly tested snapshot is as good as the latest release.
# Just keep the version number in sync with "releases" to make the
# likes of repology and distrowatch happy.```
```

Source: https://github.com/OpenMandrivaAssociation/mpv/blob/master/mpv.spec

The `mpv` issue above states good reasons for the lack of a release. It seems as though the distributions mentioned above have some kind of issue with upstream?? 

The ideal solution is to follow upstream's versioning scheme in repology. I'm not sure if issues like this have occurred in the past with other packages or if there's methods in place of alleviating it.

:+1:

**Comment by AMDmi3** [comment]
> I'm not sure if this is the right repository to open this issue

It's the right repo :+1:

> to make the likes of repology and distrowatch happy

Wow, I wasn't expecting people to start caring for Repology. However, I'm indeed not happy with fake versions mimicking official upstream releases, regardless of the upstream release policy. There's an open discussion on a well defined scheme for snapshots (which can be distinguished from the official releases and compared between each other in a meaningful way): https://github.com/repology/repology/issues/345.

> I'm not sure if issues like this have occurred in the past with other packages

They've had a lot of times. See `900.version-fixes/*` - most of rules there are for ignoring fake or snapshot versions. I'm fixing mpv issues the same way. The problem may pop up again eventually though if another repository adds `0.30.0` or different fake version greater than `0.29.1` - since we can't tell if it's another fake version or a real upstream release, it'll require updating the rule.
