### ISSUE TITLE
gentoo versioning schema not well handled

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [repology/repology-rules#359]
You can read about gentoo versioning schema here:
https://devmanual.gentoo.org/ebuild-writing/file-format/index.html
I see that packages containing `_p` (patch) or `_pre` (preview) aren't well handled, for example:
https://repology.org/project/openbgpd/versions
https://repology.org/project/whysynth/versions

Also `b` and `beta` aren't the same thing

**Comment by AMDmi3** [comment]
> You can read about gentoo versioning schema here:

I'm well aware of gentoo versioning schema, it has been discussed some times in the past.

> I see that packages containing `_p` (patch) or `_pre` (preview) aren't well handled, for example:

These are handled as good as it's possible with gentoo schema.

`_p` is ordered after corresponding release (as expected) and is ignored as there's no telling whether it means official version component (as with openbgpd), a snapshot (as with whysynth) or a mangled version (such as when `r` is replaced with `p`), while we don't want snapshot and fake versions to make real versions outdated. Note that ignored version will be treated as normal if there's equal ("confirming" it) or above (making it outdated) version from another repository. It's also possible to submit rules tuning version handling, e.g. to trust `p` for openbgpd in Gentoo). I'll do this for `openbgpd` and also merge it with `openbgpd6` which is at `6.6p0` as well, either is enough for guru version to no longer be ignored. 

`_pre` are ordered before corresponding releases and are treated as _devel_, see https://repology.org/project/creduce/information as example. I'd say that it should be ignored too, since it's used for snapshots mostly and may introduce false positives by outdating official alpha/beta versions. Probably it's just that no one complained yet.

I see no way of how this can be improved.

> Also `b` and `beta` aren't the same thing

At the end of the version they aren't and are handled accordingly: `1.0alpha` < `1.0beta` < `1.0` < `1.0a` < `1.0b` < `1.0c` ...). In the middle they definitely are or should be handled as such, because many repositories shorten `alpha`/`beta` to `a`/`b` but still need to be comparable. I haven't seen any cases of `a`/`b` having other meaning than `alpha`/`beta` yet.
