### ISSUE TITLE
dnstwist on Debian: 0~20201228-1 not detected as snapshot version

### ISSUE THREAD

**Issue by olifre** [repology/repology-rules#454]
The version of `dnstwist` in Debian:
https://packages.debian.org/testing/source/dnstwist
is `0~20201228-1`, which is a snapshot from `20201228` prefixed with `0~`. 

Currently, repology detects this as `0`. I see on the webpage that this has already been reported, but rejected, the reporter assumed this `0~20201228-1` pattern is used to avoid introducing an epoch if upstream switches to useful versions at some point. 

Could you please explain the rejection? 
If this is considered an upstream version naming bug (i.e. epochs must be used), I can take care of reporting this to Debian.

**Comment by AMDmi3** [comment]
YYYYMMDD looks like official versioning scheme, used both in tags and on PyPI, while Debian scheme is incompatible and incorrect.

**Comment by wiene** [comment]
> There's not much to explain - YYYYMMDD looks like official versioning scheme

Actually dnstwist changed its versioning scheme during its history. It started out using conventional versions (see e. g. [v1.00](https://github.com/elceef/dnstwist/releases/tag/v1.00), [v1.01](https://github.com/elceef/dnstwist/releases/tag/v1.01), [v1.02](https://github.com/elceef/dnstwist/releases/tag/v1.02)) and switched to a date based versioning scheme later on. Such changes in versioning scheme (in particular if it happens in the opposite direction, namely from date versioning to conventional versioning) can confuse many tools. If this happens, the only option would be to introduce [epochs](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version) to fix apparent backward jumps in version numbers. Since [epochs should be used sparingly](https://www.debian.org/doc/debian-policy/ch-controlfields.html#epochs-should-be-used-sparingly), Debian introduced the recommendation to prepend date based version numbers with "0~" for new packages entering Debian to avoid introducing epochs in case upstream changes its versioning scheme. To cite the [information from the Debian lint tool](https://salsa.debian.org/lintian/lintian/-/commit/0d3ba2c4e27adf62b21f10679a06188f9896e95b):

> Packages using date-based version numbering should use a "0~" prefix
> (eg. 0~20201612-1 or similar) to avoid having to introduce an epoch if
> upstream starts tagging releases in a more conventional manner.

See https://bugs.debian.org/953036 for more information on this.

**Comment by AMDmi3** [comment]
This case is exactly what epochs are designated for, and date-based scheme, as long as it's official, is not different from any other scheme to justify version scheme mangling - the latter is in fact what _confuses many tools_.
