### ISSUE TITLE
Can this be used to convert dependency names across distros?

### ISSUE THREAD

**Issue by hwittenborn** [repology/repology-rules#474]
I'm trying to convert some dependency names from one distro to another(Arch to Debian) for a script I'm working on, and a person brought me here to check everything out. I've looked around a bit, but I was wondering if the stuff in this would work for that(or rather, if it's designed for that to make that process easier).

I've looked around the website and briefly in the issues, but I haven't found anything that's letting me know if this'll work well for it. Would anyone know if the stuff here would help?

**Comment by AMDmi3** [comment]
There is an experimental [tool](https://repology.org/api/experimental/distromap) for that, but it may be lacking for you needs. Notably, it currently only supports source package names (which are also not defined for all repositories) and skips identity mappings, making these indistinguishable from missing ones. Also, since Repology works with projects which are less granular entity than packages, package mappings would always be imprecise. For example, imagemagick consists of libraries and command line utilities, and you may want to map imagemagick library package from one repo to another, but repology won't be able to do that, mapping to both library and utilities (and everything else belonging to the same project).

**Comment by hwittenborn** [comment]
Just looking at some more stuff, but it looks like the [API](https://repology.org/api) will work for my needs given I just feed it the packages I'm looking at.

Unless you have any objections/things I'm missing, I think I'm good to go now.

**Comment by AMDmi3** [comment]
I'm fine with that, as long as you limit the access rate reasonably (1RPS or less).
You may also need https://repology.org/tools/project-by to start from package names.

**Comment by hwittenborn** [comment]
All looks good, thanks 👌🏻
