### ISSUE TITLE
Accused of fake version

### ISSUE THREAD

**Issue by firasuke** [repology/repology-rules#645]
Thanks for the addition of glaucus!

I was checking the rules and I stumbled upon the following:

https://github.com/repology/repology-rules/blob/2ab9fbea35d0f2277b062554a8f20fd9986df792/900.version-fixes/lib.yaml#L85

I'd like to inquire about the meaning of this? Is it because `libelf` lacks a `url`?

To clarify, the version of `libelf` I'm using is the one from `elfutils` which is currently at `0.187`.

This is not the same as the version provided by some distributions which is a standalone [`libelf`](http://www.mr511.de/software/libelf-0.8.13.tar.gz) with a version number of `0.8.13`.

Thanks again!

**Comment by AMDmi3** [comment]
That's a common way of handling incorrect versions (mark specific version and incorrect and mark other potential versions from that source as untrusted). Absence of url is not the direct cause of it, but because of that the package is not associated with elfutils. Anyway these entries are no longer relevant as the package is no longer parsed.

**Comment by sskras** [comment]
Well, at least I see a name collision between two unrelated `libelf` implementations as a root cause of the confusion.
