### ISSUE TITLE
can-utils has a valid versioning scheme

### ISSUE THREAD

**Issue by Luflosi** [repology/repology-rules#698]
**Projects affected**
https://repology.org/project/can-utils/versions

---
All can-utils packages are marked as noscheme but this is now incorrect. Most versions listed on the repology website correspond to actual release tags: https://github.com/linux-can/can-utils/tags.

**Comment by AMDmi3** [comment]
> which are marked as outdated but should probably be marked differently

Not really. Repology does not provide any guarantees regarding garbage versions handling, so technically it "should" be anything which does not pessimize genuine versions. On practice it's usually _outdated_ for versions which compare less than newest and _incorrect_ for versions which compare greater. For `0.0+git*` versions it happens to be correct, as these dates are, in fact, outdated. `946.cfe4196` actually points to the same commit as 2023.03, but the package seems to fetch latest commit instead, there's no way to handle this in any meaningful way at all.

> Also, can you please explain why sink: true is needed?

It makes versions like `20170830` and `20160229git` classified as outdated (which is known from the dates) instead of incorrect. It's completely optional, just a little classification improvement.
