### ISSUE TITLE
What's the best way to deal with R-Forge?

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-rules#741]
**Projects affected**
Any R project could be affected.  A current example is [r:numderiv](https://repology.org/project/r:numderiv/versions)

**Observed behavior**
[CRAN](https://cran.r-project.org/) is the reference for current CRAN modules.
However, there is another site used for the development of new modules -- where you can get beta versions: [R-Forge](http://optimizer.r-forge.r-project.org/)

**Expected behavior**
An R-Forge version that is higher than the CRAN version should not be consider a release.  In the numderiv example above (which has existed for months) only one repository has it, and it's been masking the true CRAN release.

My suggestion is that all packages from R-forge be considered "devel" or untrusted or something.  I'm not sure if this is the best approach, hence the created issue for the discussion.

Hopefully the premise that R-Force can't trump CRAN is agreed though.  CRAN should be the reference.

**Comment by AMDmi3** [comment]
I have no thoughts on this, better ask upstream. For instance, Paul Gilbert, author of numderive, is also project member on r-forge.

**Comment by pdgilbert** [comment]
I think it would be correct to consider CRAN the reference. R-Forge really is like github. (It predates github and may never have existed if github had come along a few years sooner.) Using an R-forge version would be like using the latest github commit. You should not even consider that a devel release, even though it has a new release number. Some of the CI testing requires a release number, which cannot include text like "alpha" and "beta", so it is pretty common just to stick in a guess of what the next release number will be.

CRAN has a very serious testing filter when packages are submitted. The filter evolves with new releases of R, so it can be onerous to submit to CRAN. Packages do get removed from CRAN if they start failing with new R releases, but when a new package release is submitted it is held to a new higher standard than a package version which is already on CRAN.

In the case of my package numDeriv, on R-Forge I have used version numbers 2020.2-1 and 2022.9-1 since the CRAN release 2016.8-1. There  is no change in the code in these R-Forge versions. The first has German and Korean translation of messages, but these do not work properly unless language support is installed. The second has a license change from GPL-2 to GPL >= 2. That was at the request of someone who was facing a licensing conflict in there own package. The R-Forge version has been adequate for  them.

Hope this helps.

**Comment by pdgilbert** [comment]
BTW, R can use packages from repositories other than CRAN. The only one I know of is [Bioconductor ](https://www.bioconductor.org/)

**Comment by jrmarino** [comment]
Thanks @pdgilbert 
so @AMDmi3 , can a rule be developed auto automatically marks r-forge sources the same as git snapshots?

**Comment by AMDmi3** [comment]
@pdgilbert thank you so much for the explanation.
@jrmarino added. It checks homepage, so is not completely reliable. If other cases appear we'll have to fix them with individual rules.
