### ISSUE TITLE
freebsd: invalid version scheme

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#82]
https://repology.org/metapackage/amass/versions
https://github.com/OWASP/Amass/releases
must be 2.6.0

**Comment by AMDmi3** [comment]
FreeBSD is getting annoying with these fake versions. These are actually caused by the ease of pointing a FreeBSD port to a commit past the tag:

https://github.com/freebsd/freebsd-ports/blob/de29bebff4df192104121856e8673b2344ef2c51/dns/amass/Makefile#L5-L6

There's no way to detect this pattern through the INDEX file we're using. As Repology maintainer I'd probably mark whole FreeBSD as untrusted after a few more cases, but as FreeBSD port maintainer myself I plan to set up an alternative port metadata dump. FreeBSD portstree contain a lot of useful data not available through INDEX which will be useful for Repology.

@yurivict you may have some comments, as you happen to use this pattern (airspy, flann, amass, swh-lv2 ports).

**Comment by yurivict** [comment]
> FreeBSD should create an additional suffix instead of extending (faking) the version. For example, we use <version>_p<date> or <version>-r<revision> in Gentoo.

Ok, tell this to portmgr.

**Comment by blshkv** [comment]
@yurivict  I have looked at the freebsd Makefile and didn't get it:
```
DISTVERSION=	2.6.0-11
DISTVERSIONSUFFIX=	-g1ef5a43
````

What was the reason of faking ```-11``` in that particular case?
I can't find commit ```g1ef5a43``` and the current release compiles just fine.

**Comment by yurivict** [comment]
This isn't faking, this is the way recommended by portmgr. Without ```-11``` it won't get into the version at all.

I agree with you, this isn't an optimal vway of dealing with this problem. They should add a tag like ```DISTVERSIONREV``` and put ```-11``` there, and then use ```_p``` or ```-r```. But I can't do anything about this, this is for ```portmgr@```.

**Comment by blshkv** [comment]
got it, thank you for the explanation
