### ISSUE TITLE
`0-unstable-2024-01-10` is marked as outdated compared to `2022-03-07`

### ISSUE THREAD

**Issue by Sigmanificient** [repology/repology-rules#837]
**Projects affected**

https://repology.org/project/apl386/versions

**Observed behavior**

The oldest version `2022-03-07` is considered to be the latest version, while `0-unstable-2024-01-10` is considered outdated.

**Expected behavior**

`2022-03-07` is from the previous nixpkgs channel, and it was following the old version scheme (`unstable-YYYY-MM-DD`). It has since been migrated to newest `LATEST-unstable-YYYY-MM-DD` (lastest being `0` in this case).

Thus, `0-unstable-2024-01-10` should be the most recent version

In case the 2 dates are the same:
`littlegptracker` is at `0-unstable-2020-11-26` and marked as outdated compared to version `2020-11-26` (same date)

**Comment by Sigmanificient** [comment]
Packages subject to the similar issue:
- https://repology.org/project/visualizer
- https://repology.org/project/asc-key-to-qr-code-gif/versions

**Comment by AMDmi3** [comment]
Feel free to submit `noscheme` rules for these. Please attach links which confirm that these really do not have official releases.

**Comment by Sigmanificient** [comment]
hum is there any way to automate this, because there might be quite more than just the examples i gaves

**Comment by Sigmanificient** [comment]
@AMDmi3

**Comment by AMDmi3** [comment]
Wait, in fact most of your cases were fixed in #823, but it turns out that not all projects were updated to be affected by the fix. I've force updated these. To be clear, this fixed only specific case where a project is only packaged in nix and old snapshot scheme outdates new one - these cases are numerous and it's possible to ignore these and save us some rules, though the fix is actually a hack. However, it won't affect cases where a project is packaged in other repositories as well - these will still need `noscheme`, otherwise repositories will randomly outdate each other.
 
> Marking them as such would cause repology to not treat them, and thus their packages would loss meaning and comparison point, which does not seems like a right solution.
 
No, that's exactly what we want to do. There's no way to compare snapshots, because schemes are incompatible (not everyone uses dates to begin with), dates are incompatible (you can't expect everyone to use last commit date and not $now, also dates are affected by timezones), and even if these were comparable it would make sense not to compare these are the same way as releases because in actively developed project snapshot date would tick every day and that would only annoy most maintainers.
